name: test branch then deploy a preview
on:
  push:
     branches-ignore:
        - main
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run
        run: npm run start &

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run playwright tests
        run: npm run test:e2e

  vitest:
    name: vitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci
      - name: Run tests
        run: npm run test
        
        

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [vitest, playwrighttests]
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

