name: test on push
on:
  push:
    branches: main
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci

      - name: Build
        run: npm run build
      - name: Run
        run: npm run start &
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run playwright tests
        run: npx run test:e2e

  vitest:
    name: vitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci
      - name: Run tests
        run: npm run test
