name: test on push
on:
  push:
    branches: main
jobs:
  playwrighttests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci

      - name: Run playwright tests
        run: npx run test:e2e

  vitest:
    name: vitest
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci
      - name: Run tests
        run: npm run test

      - name: coverage test
        run: npx vitest --coverage
      - name: "Report Coverage"
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v1
